### ISSUE TITLE
Forge 1.20.2 has incompatibility with Architectury 9.0.8

### ISSUE THREAD

**Issue by boholder** [minecraft-access/minecraft-access#182]
```log
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-10-03 21:18:13
Description: Mod loading error has occurred
...

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dev.architectury.networking.forge.NetworkManagerImpl.<clinit>(NetworkManagerImpl.java:91) ~[architectury-9.0.8-forge.jar%23158!/:?] {re:classloading}
-- MOD architectury --
Details:
	Mod File: /C:/Users/Administrator/AppData/Roaming/.minecraft/mods/architectury-9.0.8-forge.jar
	Failure message: Architectury (architectury) has failed to load correctly
		java.lang.NoSuchMethodError: 'net.minecraftforge.network.event.EventNetworkChannel net.minecraftforge.network.NetworkRegistry.newEventChannel(net.minecraft.resources.ResourceLocation, java.util.function.Supplier, java.util.function.Predicate, java.util.function.Predicate)'
	Mod Version: 9.0.8
	Mod Issue URL: https://github.com/shedaniel/architectury/issues
	Exception message: java.lang.NoSuchMethodError: 'net.minecraftforge.network.event.EventNetworkChannel net.minecraftforge.network.NetworkRegistry.newEventChannel(net.minecraft.resources.ResourceLocation, java.util.function.Supplier, java.util.function.Predicate, java.util.function.Predicate)'
Stacktrace:
	at dev.architectury.networking.forge.NetworkManagerImpl.<clinit>(NetworkManagerImpl.java:91) ~[architectury-9.0.8-forge.jar%23158!/:?] {re:classloading}
	at java.lang.Class.forName0(Native Method) ~[?:?] {}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.20.2-48.0.13.jar%23162!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.20.2-48.0.13.jar%23162!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.20.2-48.0.13.jar%23162!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.2-48.0.13.jar%23161!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.20.2
	Minecraft Version ID: 1.20.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
```

Will trying to make the 1.20 version of mod works on both 1.20.1 and 1.20.2. Hope we can resolve this problem by simply upgrade Architectury's version. I doubt that we can do this since we have other dependencies (like the game version).
https://github.com/khanshoaib3/minecraft-access/blob/1.20/gradle.properties

Sadly to know that the `1.20.2` (client) is not compatible with `1.20.0/1.20.1` (server) from the wiki page.
https://minecraft.wiki/w/Java_Edition_1.20.2
If we must upgrade the `1.20` version of mod to game version `1.20.2`, there will be no new version of mod for game `1.20.1`. We may need to run a poll to see if anyone is playing on `1.20.0/1.20.1` multiplayer mode.

Newest Architectury API `v10.0.8` (for `1.20.2`)
https://modrinth.com/mod/architectury-api/changelog
API `v10` for `1.20.2`, `v9` for `1.20.0` (and `1.20.1`?) 
https://docs.architectury.dev/api/migration/version_10

Checkllist:

* [ ] Works on Fabric 1.20.1
* [ ] Works on Fabric 1.20.2
* [ ] Works on Forge 1.20.1
* [ ] Works on Forge 1.20.2

**Comment by boholder** [comment]
Newest Architectury API `v10.0.8` (for `1.20.2`): https://modrinth.com/mod/architectury-api/changelog
API `v10` for `1.20.2`, `v9` for `1.20.0` (and `1.20.1`?) 
https://docs.architectury.dev/api/migration/version_10
